/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Slight modifications afterwards.
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Sand: THREE.Mesh
  }
  materials: {
    custom_sand_material: THREE.MeshStandardMaterial
  }
};

export function Sand(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sand_plain.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Sand"
        castShadow
        receiveShadow
        geometry={nodes.Sand.geometry}
        material={materials.custom_sand_material}
      />
    </group>
  )
}

useGLTF.preload('/models/sand_plain.glb');
